fileVersion: 1
id: "3"
mappingDefinitions:
  DESTINATION:
    database: DAVID_I_EDW
    schema: ENVIRONMENT_STAGING
  SOURCE:
    database: COALESCE_SAMPLE_DATABASE
    schema: TPCH_SF001
name: My First Environment
type: Environment
